import torch
import torch.nn as nn
import numpy as np
import math
import os
import urllib.request

class SineLayer(nn.Module):
    def __init__(self, in_features, out_features, bias=True, is_first=False, omega_0=30):
        super().__init__()
        self.omega_0 = omega_0
        self.is_first = is_first
        self.linear = nn.Linear(in_features, out_features, bias=bias)
        self.init_weights()
    
    def init_weights(self):
        with torch.no_grad():
            if self.is_first:
                self.linear.weight.uniform_(-1 / self.linear.in_features, 1 / self.linear.in_features)      
            else:
                self.linear.weight.uniform_(-math.sqrt(6 / self.linear.in_features) / self.omega_0, 
                                            math.sqrt(6 / self.linear.in_features) / self.omega_0)
        
    def forward(self, input):
        return torch.sin(self.omega_0 * self.linear(input))

class SIREN(nn.Module):
    def __init__(self, in_features=3, hidden_features=16, hidden_layers=1, out_features=1, outermost_linear=True):
        super().__init__()
        self.net = []
        self.net.append(SineLayer(in_features, hidden_features, is_first=True))
        for i in range(hidden_layers):
            self.net.append(SineLayer(hidden_features, hidden_features, is_first=False))
            
        if outermost_linear:
            final_linear = nn.Linear(hidden_features, out_features)
            with torch.no_grad():
                final_linear.weight.uniform_(-math.sqrt(6 / hidden_features) / 30, 
                                              math.sqrt(6 / hidden_features) / 30)
            self.net.append(final_linear)
        else:
            self.net.append(SineLayer(hidden_features, out_features, is_first=False))
            
        self.net = nn.Sequential(*self.net)
    
    def forward(self, coords):
        return self.net(coords)

class HyperRNN(nn.Module):
    def __init__(self, vocab_size, hidden_size):
        super().__init__()
        # 3 inputs (x, y, z layer id) -> 32 hidden -> 1 output
        self.siren = SIREN(in_features=3, hidden_features=32, hidden_layers=2, out_features=1)
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        
        self.register_buffer('coords_ih', self._make_grid(vocab_size, hidden_size, -1.0))
        self.register_buffer('coords_hh', self._make_grid(hidden_size, hidden_size, 0.0))
        self.register_buffer('coords_out', self._make_grid(hidden_size, vocab_size, 1.0))
        
        num_params = sum(p.numel() for p in self.parameters())
        virtual_params = (vocab_size * hidden_size) + (hidden_size * hidden_size) + (hidden_size * vocab_size)
        print(f"--- HYPER-SIREN INITIALIZED ---")
        print(f"Stored DNA parameters: {num_params} (Approx {num_params * 4 / 1024:.2f} KB)")
        print(f"Virtual Matrix Size: {virtual_params} Parameters")
        print(f"Compression Ratio: {virtual_params / num_params:.2f}x")
        
    def _make_grid(self, in_feat, out_feat, z_val):
        x = torch.linspace(-1, 1, in_feat)
        y = torch.linspace(-1, 1, out_feat)
        grid_y, grid_x = torch.meshgrid(y, x, indexing='ij')
        z = torch.full_like(grid_x, z_val)
        return torch.stack([grid_x, grid_y, z], dim=-1).reshape(-1, 3)
        
    def forward(self, x, hidden=None):
        batch, seq = x.shape
        if hidden is None:
            hidden = torch.zeros(batch, self.hidden_size, device=x.device)
            
        # 1. SYNTHESIZE VIRTUAL WEIGHTS (Dynamically generated by SIREN)
        # We scale the SIREN output (-1 to 1) down to typical weight initialization variance
        scale = 2.0 / math.sqrt(self.hidden_size)
        
        W_ih = self.siren(self.coords_ih).reshape(self.hidden_size, self.vocab_size) * scale
        W_hh = self.siren(self.coords_hh).reshape(self.hidden_size, self.hidden_size) * scale
        W_out = self.siren(self.coords_out).reshape(self.vocab_size, self.hidden_size) * scale
        
        # 2. STANDARD RNN PASS
        x_onehot = torch.nn.functional.one_hot(x, self.vocab_size).float()
        ih_proj = torch.matmul(x_onehot, W_ih.t())
        
        out = []
        for t in range(seq):
            hh_proj = torch.matmul(hidden, W_hh.t())
            hidden = torch.tanh(ih_proj[:, t, :] + hh_proj)
            logits = torch.matmul(hidden, W_out.t())
            out.append(logits)
            
        return torch.stack(out, dim=1), hidden

def get_batch(text, seq_length, batch_size, char_to_ix):
    ixs = torch.randint(0, len(text) - seq_length - 1, (batch_size,))
    x = torch.zeros(batch_size, seq_length, dtype=torch.long)
    y = torch.zeros(batch_size, seq_length, dtype=torch.long)
    for i, idx in enumerate(ixs):
        x[i] = torch.tensor([char_to_ix[ch] for ch in text[idx:idx+seq_length]])
        y[i] = torch.tensor([char_to_ix[ch] for ch in text[idx+1:idx+seq_length+1]])
    return x, y

def main():
    if not os.path.exists("tinyshakespeare.txt"):
        url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
        urllib.request.urlretrieve(url, "tinyshakespeare.txt")

    with open("tinyshakespeare.txt", "r") as f:
        text = f.read()

    chars = sorted(list(set(text)))
    vocab_size = len(chars)
    char_to_ix = {ch: i for i, ch in enumerate(chars)}
    
    device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    # 512 Hidden Dims
    model = HyperRNN(vocab_size, hidden_size=512).to(device)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=0.005)
    criterion = nn.CrossEntropyLoss()
    
    batch_size = 128
    seq_length = 32
    
    print("Training the DNA...")
    for step in range(500):
        x, y = get_batch(text, seq_length, batch_size, char_to_ix)
        x, y = x.to(device), y.to(device)
        
        optimizer.zero_grad()
        logits, _ = model(x)
        
        loss = criterion(logits.reshape(-1, vocab_size), y.reshape(-1))
        loss.backward()
        optimizer.step()
        
        if step % 50 == 0:
            perplexity = torch.exp(loss)
            print(f"Step {step} | Loss: {loss.item():.4f} | Perplexity: {perplexity.item():.4f}")

if __name__ == '__main__':
    main()
